version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: research_admin
      POSTGRES_PASSWORD: V9r8kLm2pXqTf7Z1
      POSTGRES_DB: research_project
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgres://research_admin:V9r8kLm2pXqTf7Z1@db:5432/research_project
      REDIS_URL: redis://redis:6379
      TS_NODE_PROJECT: /app/api/tsconfig.build.json

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redis:
