version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: research_admin
      POSTGRES_PASSWORD: V9r8kLm2pXqTf7Z1
      POSTGRES_DB: research_project
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://research_admin:V9r8kLm2pXqTf7Z1@db:5432/research_project
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  pgdata:
